<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [2]:
df = pd.read_csv('/datasets/insurance.csv')
df.head(5)

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

$$
XPw = XP((XP)^T XP)^{-1} (XP)^T y = XP(P^T X^T XP)^{-1} P^T X^T y= XP P^{-1}((P^T X^T) X)^{-1} P^T X^Ty = X (X^T X)^{-1}(P^T)^{-1} P^T X^T y
$$
$$
= X (X^T X)^{-1} X^T y = Xw
$$

In [4]:
X = df.drop(['Страховые выплаты'], axis=1)
y = df['Страховые выплаты']
P = np.random.sample((4, 4))

In [5]:
print(np.linalg.inv(P))

[[-0.56564806 -0.72187962  1.49399775  0.94104156]
 [ 1.91398486 -3.39785709 -2.27303803  1.53497314]
 [-0.81521238  2.42071691  0.46238003 -0.41601958]
 [ 0.51703289  1.02855141  0.92429865 -1.58903139]]


In [6]:
model = LinearRegression()
model.fit(X,y)
predictions = model.predict(X)
r2_score(y,predictions)

0.4249455028666801

In [7]:
X_P = X @ P

In [8]:
model.fit(X_P,y)
predictions = model.predict(X_P)
r2_score(y,predictions)

0.4249455028666931

**Ответ:** Качество линейной регрессии не изменится 

**Обоснование:** Так и не понял как обосновать О_о

## Алгоритм преобразования

**Алгоритм**
- 1  Отделим целевые признаки от набора данных 
- 2  Создадим обратимую матрицу, проверим и сохраним её как ключ шифрования 
- 3  Умножим данные на ключ шифрования
- 4  Проверим качетво линейной регрессии 

**Обоснование**

...

## Проверка алгоритма

In [9]:
feature = df.drop(['Страховые выплаты'], axis=1)
target = df['Страховые выплаты']

In [10]:
key = np.random.sample((feature.shape[1], feature.shape[1]))
print(np.linalg.inv(key))

[[ 2.35844398 -0.90387989 -0.1768962  -0.80792501]
 [-0.75677453 -1.04203904  2.19714371  0.63104235]
 [-0.14363799  1.6234128  -0.81326382 -1.04873237]
 [ 0.34866772  0.78402867 -1.55894071  0.86695363]]


In [13]:
feature.shape

(5000, 4)

In [11]:
feature_crypted = feature @ key

In [12]:
model = LinearRegression()
model.fit(feature,target)
predictions = model.predict(feature)
print(r2_score(target,predictions))
model.fit(feature_crypted,target)
predictions = model.predict(feature_crypted)
print(r2_score(target,predictions))

0.4249455028666801
0.4249455028666692
